export const ADD_GAME_TYPE_THREE_SUCCESSFUL = 'ADD_GAME_TYPE_THREE_SUCCESSFUL';
export const LOAD_PRIZES_SUCCESSFUL = 'LOAD_PRIZES_SUCCESSFUL';
export const LOAD_USER_GIFT_BALANCES_SUCCESSFUL = 'LOAD_USER_GIFT_BALANCES_SUCCESSFUL';
export const LOAD_DENOMINATIONS_SUCCESSFUL = 'LOAD_DENOMINATIONS_SUCCESSFUL';
export const ADD_TOURNAMENT_SUCCESSFUL = 'ADD_TOURNAMENT_SUCCESSFUL';
export const LOAD_TOURNAMENT_SUCCESSFUL = 'LOAD_TOURNAMENT_SUCCESSFUL';
export const LOAD_ENGAGEMENT_BY_ID = 'LOAD_ENGAGEMENT_BY_ID';
